# Generated by Django 2.2.2 on 2019-06-20 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authjwt', '0002_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Ukraine phone number like '+380111111111'", regex='^\\+380((\\d){9})$')], verbose_name='phone number'),
        ),
    ]
