# Generated by Django 2.2.1 on 2019-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0002_auto_20190519_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='F7DC6F', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateTimeField(default='P1M'),
        ),
    ]
