# Generated by Django 2.2.1 on 2019-05-21 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0003_auto_20190521_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 10, 17, 5, 611446, tzinfo=utc)),
        ),
    ]
