# Generated by Django 2.2.1 on 2019-05-21 10:19

from django.db import migrations, models
from django.utils import timezone
import project.spa.models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0004_auto_20190521_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
