# Generated by Django 2.2.1 on 2019-05-21 10:32

from django.db import migrations, models
import project.spa.models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0005_auto_20190521_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, default='\n        What is Lorem Ipsum? Lorem Ipsum is simply dummy text of the printing and typesetting industry.\n    ', max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='final_date',
            field=models.DateTimeField(default=project.spa.models.plus_month),
        ),
    ]
