# Generated by Django 2.2.1 on 2019-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0007_auto_20190521_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='shared',
            field=models.BooleanField(default=False, help_text='Will be hidden for everyone'),
        ),
    ]
