# Generated by Django 2.2.1 on 2019-05-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0008_project_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='task',
        ),
    ]
