# Generated by Django 2.2.1 on 2019-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0009_auto_20190522_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='shared',
        ),
        migrations.AddField(
            model_name='task',
            name='shared',
            field=models.BooleanField(default=False, help_text='Will be hidden for everyone'),
        ),
    ]
