# Generated by Django 2.2.1 on 2019-05-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0010_auto_20190522_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='shared',
        ),
        migrations.AddField(
            model_name='project',
            name='shared',
            field=models.BooleanField(default=False, help_text='Will be hidden for everyone'),
        ),
    ]
